/soc/oplus,comm/oplus_spec,full-pre-ffc-mv 0x1210
/soc/oplus,comm/oplus_spec,vbat_uv_thr_mv 0xaf0
/soc/oplus,comm/oplus,chg_shutdown_max_mv 0xa8c
/soc/oplus,comm/oplus_spec,vbat_charging_uv_thr_mv 0xa8c
/soc/oplus,comm/oplus_spec,sw-fv-mv 0x1210 0x1210 0x1210 0x1210 0x1210 0x1210 0x1210 0x11e9 0x11e9
/soc/oplus,comm/oplus_spec,fv-mv 0x1216 0x1216 0x1216 0x1216 0x1216 0x1216 0x1210 0x1210 0x1210
d /soc/oplus,comm/smooth_strategy/oplus_spec,reserve_table_centipercent
a /soc/oplus,comm/smooth_strategy/oplus_spec,reserve_table_centipercent 0x00 0x64 0x00 0x00 0x00 0x64

