/soc/oplus,monitor/track,nominal_fcc1 0x17b2
/soc/oplus,monitor/track,gauge_max_dischg_curr 0x1b58
/soc/oplus,monitor/track,nominal_qmax1 0x17b2
/soc/oplus,monitor/track,gauge_max_cell_vol 0x1210
a /soc/oplus,monitor/track,nominal_qmax2 0x17b2

